#! /usr/bin/env python

import sys
import time
import dbus

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object("org.bluez", "/"),
						"org.bluez.Manager")


adapter_path = dbus.Interface(bus.get_object("org.bluez",

hid_server = dbus.Interface(bus.get_object("org.bluez", manager.DefaultAdapter()),
							"org.bluez.GenericHID")

hid_server.SendEvent(0, 0, 0)
